---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/desource/fedora-build

inputs:
  - name: pipeline
    path: src

outputs:
  - name: glibc-build
  
run:
  path: ./src/glibc/build.sh
