jobs:
- name: concourse
  plan:
  - do:
    - aggregate:
      - get: container
        resource: concourse-container
      - get: glibc-ci
    - task: glibc
      file: glibc-ci/build.yaml
    - task: concourse
      file: container/build.yaml
    - put: concourse-docker
      params:
        build: out
        tag: out/tag

resources:
- name: glibc-ci
  type: git
  source:
    uri: https://github.com/desource/glibc.git

- name: concourse-container
  type: git
  source:
    uri: https://github.com/desource/concourse-container.git

- name: concourse-docker
  type: docker-image
  source:
    repository: quay.io/desource/concourse
    username: {{quay-io-username}}
    password: {{quay-io-password}}
