groups:
- name: containers
  jobs:
    - haproxy
    - nginx
    - java
    - elasticsearch
    - nodejs
    - kibana
    - heka
    - skydns
- name: base
  jobs:
    - centos-7
    - ubuntu-trusty
    - ubuntu-xenial
- name: build
  jobs:
    - alpine-build
    - fedora-build

resources:
- name: pipeline
  type: git
  source:
    uri: https://github.com/desource/pipeline.git

- name: notification
  type: notification
  source:
    url: {{slack-notifications-url}}

- name: haproxy-src
  type: git
  source:
    uri: https://github.com/desource/container-haproxy.git

- name: nginx-src
  type: git
  source:
    uri: https://github.com/desource/container-nginx.git

- name: libressl-src
  type: git
  source:
    uri: https://github.com/desource/libressl.git

- name: glibc-src
  type: git
  source:
    uri: https://github.com/desource/glibc.git

- name: java-src
  type: git
  source:
    uri: https://github.com/desource/container-java.git

- name: elasticsearch-src
  type: git
  source:
    uri: https://github.com/desource/container-elasticsearch.git

- name: nodejs-src
  type: git
  source:
    uri: https://github.com/desource/container-nodejs.git

- name: kibana-src
  type: git
  source:
    uri: https://github.com/desource/container-kibana.git

- name: heka-git
  type: git
  source:
    uri: git@github.com:markuskobler/heka.git
    private_key: {{github-private-key}}
    branch: dev

- name: heka-container-src
  type: git
  source:
    uri: https://github.com/desource/container-heka.git

- name: skydns-git
  type: git
  source:
    uri: https://github.com/skynetservices/skydns.git
    branch: 2.5.3a

- name: skydns-container-src
  type: git
  source:
    uri: https://github.com/desource/container-skydns.git

- name: alpine-build-image
  type: docker-image
  source:
    repository: quay.io/desource/alpine-build
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: fedora-build-image
  type: docker-image
  source:
    repository: quay.io/desource/fedora-build
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: centos-7-image
  type: docker-image
  source:
    repository: quay.io/desource/centos-7
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: ubuntu-trusty-image
  type: docker-image
  source:
    repository: quay.io/desource/ubuntu-trusty
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: ubuntu-xenial-image
  type: docker-image
  source:
    repository: quay.io/desource/ubuntu-xenial
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: haproxy-docker
  type: docker-image
  source:
    repository: quay.io/desource/haproxy
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: nginx-docker
  type: docker-image
  source:
    repository: quay.io/desource/nginx
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: java-docker
  type: docker-image
  source:
    repository: quay.io/desource/java
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: elasticsearch-docker
  type: docker-image
  source:
    repository: quay.io/desource/elasticsearch
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: nodejs-docker
  type: docker-image
  source:
    repository: quay.io/desource/nodejs
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: kibana-docker
  type: docker-image
  source:
    repository: quay.io/desource/kibana
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: skydns-docker
  type: docker-image
  source:
    repository: quay.io/desource/skydns
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: heka-docker
  type: docker-image
  source:
    repository: quay.io/desource/heka
    username: {{quay-io-username}}
    password: {{quay-io-password}}

jobs:
- name: haproxy
  plan:
  - do:
    - aggregate:
      - get: pipeline
      - get: src
        resource: haproxy-src
        trigger: true
      - get: libressl-src
        trigger: true
    - aggregate:
      - task: libressl
        file: libressl-src/build.yaml
      - task: lua
        file: pipeline/lua/build.yaml
      - task: libslz
        file: pipeline/libslz/build.yaml
    - task: haproxy
      file: src/build.yaml
    - put: haproxy-docker
      params:
        build: out
    on_failure:
      put: notification
      params:
        text: Failed to build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"
    on_success:
      put: notification
      params:
        text: Built https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"

- name: nginx
  plan:
  - do:
    - aggregate:
      - get: src
        resource: nginx-src
        trigger: true
      - get: libressl-src
        trigger: true
    - aggregate:
        - task: libressl
          file: libressl-src/build.yaml
    - task: nginx
      file: src/build.yaml
    - put: nginx-docker
      params:
        build: out
    on_failure:
      put: notification
      params:
        text: Failed to build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"
    on_success:
      put: notification
      params:
        text: Built https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"

- name: java
  plan:
  - do:
    - aggregate:
      - get: java-src
        trigger: true
      - get: glibc-src
        trigger: true
    - task: glibc
      file: glibc-src/build.yaml
    - task: java
      file: java-src/build.yaml
    - put: java-docker
      params:
        build: out
    on_failure:
      put: notification
      params:
        text: Failed to build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"
    on_success:
      put: notification
      params:
        text: Built https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"

- name: elasticsearch
  plan:
  - do:
    - aggregate:
        - get: java-docker
          passed: [java]
          trigger: true
        - get: elasticsearch-src
          trigger: true
    - task: elasticsearch
      file: elasticsearch-src/build.yaml
    - put: elasticsearch-docker
      params:
        build: out
    on_failure:
      put: notification
      params:
        text: Failed to build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"
    on_success:
      put: notification
      params:
        text: Built https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"

- name: nodejs
  plan:
  - do:
    - get: src
      resource: nodejs-src
      trigger: true
    - task: nodejs
      file: src/build.yaml
    - put: nodejs-docker
      params:
        build: out
    on_failure:
      put: notification
      params:
        text: Failed to build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"
    on_success:
      put: notification
      params:
        text: Built https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"

- name: kibana
  plan:
  - do:
    - aggregate:
      - get: nodejs-docker
        passed: [nodejs]
        trigger: true
      - get: src
        resource: kibana-src
        trigger: true
    - task: kibana
      file: src/build.yaml
    - put: kibana-docker
      params:
        build: out
    on_failure:
      put: notification
      params:
        text: Failed to build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"
    on_success:
      put: notification
      params:
        text: Built https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"

- name: heka
  plan:
  - do:
    - aggregate:
      - get: src
        resource: heka-git
        trigger: true
      - get: heka-container-src
        trigger: true
    - task: heka
      file: heka-container-src/build.yaml
    - put: heka-docker
      params:
        build: out
    on_failure:
      put: notification
      params:
        text: Failed to build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"
    on_success:
      put: notification
      params:
        text: Built https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        icon_emoji: ":concourse:"

- name: skydns
  plan:
  - do:
    - aggregate:
      - get: skydns-git
      - get: skydns-container-src
        trigger: true
    - task: skydns
      file: skydns-container-src/build.yaml
    - put: skydns-docker
      params:
        build: skydns-build
    on_failure:
      put: notification
      params:
        text: Failed to build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"
    on_success:
      put: notification
      params:
        text: Built https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        channel: "#general"
        username: concourse
        always_notify: true
        icon_emoji: ":concourse:"

- name: alpine-build
  serial: true
  plan:
  - get: pipeline
  - put: alpine-build-image
    params:
      build: pipeline/build/alpine-build

- name: fedora-build
  serial: true
  plan:
  - get: pipeline
  - put: fedora-build-image
    params:
      build: pipeline/build/fedora-build

- name: centos-7
  serial: true
  plan:
  - get: pipeline
  - put: centos-7-image
    params:
      build: pipeline/base/centos-7

- name: ubuntu-trusty
  serial: true
  plan:
  - get: pipeline
  - put: ubuntu-trusty-image
    params:
      build: pipeline/base/ubuntu-trusty

- name: ubuntu-xenial
  serial: true
  plan:
  - get: pipeline
  - put: ubuntu-xenial-image
    params:
      build: pipeline/base/ubuntu-xenial

resource_types:
- name: notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
