groups:
- name: containers
  jobs:
    - haproxy
    - nginx
    - java
    - kibana
- name: base-containers
  jobs:
    - alpine-build
    - fedora-build

resources:
- name: common
  type: git
  source:
    uri: git@github.com:desource/pipeline.git
    private_key: {{github-private-key}}

- name: haproxy-src
  type: git
  source:
    uri: https://github.com/desource/container-haproxy.git
    branch: concourse

- name: nginx-src
  type: git
  source:
    uri: https://github.com/desource/container-nginx.git
    branch: concourse

- name: java-src
  type: git
  source:
    uri: https://github.com/desource/container-java.git
    branch: concourse

- name: kibana-src
  type: git
  source:
    uri: https://github.com/desource/container-kibana.git
    branch: concourse

- name: quay-io-desource-alpine-build
  type: docker-image
  source:
    repository: quay.io/desource/alpine-build
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: quay-io-desource-fedora-build
  type: docker-image
  source:
    repository: quay.io/desource/fedora-build
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: alpine-build-image
  type: docker-image
  source:
    repository: quay.io/desource/alpine-build
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: haproxy-docker
  type: docker-image
  source:
    repository: quay.io/desource/haproxy
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: nginx-docker
  type: docker-image
  source:
    repository: quay.io/desource/nginx
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: java-docker
  type: docker-image
  source:
    repository: quay.io/desource/java
    username: {{quay-io-username}}
    password: {{quay-io-password}}
    
- name: kibana-docker
  type: docker-image
  source:
    repository: quay.io/desource/kibana
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: heka-docker
  type: docker-image
  source:
    repository: quay.io/desource/heka
    username: {{quay-io-username}}
    password: {{quay-io-password}}

jobs:
- name: haproxy
  plan:
  - aggregate:
      - get: common
      - get: haproxy-src
        trigger: true
  - aggregate:
      - task: build-libressl
        file: common/libressl/build.yaml
      - task: build-lua
        file: common/lua/build.yaml
      - task: build-libslz
        file: common/libslz/build.yaml
  - task: build-haproxy
    file: haproxy-src/build.yaml
  - put: haproxy-docker
    params:
      build: haproxy-build

- name: nginx
  plan:
  - aggregate:
      - get: common
      - get: nginx-src
        trigger: true
  - aggregate:
      - task: build-libressl
        file: common/libressl/build.yaml
  - task: build-nginx
    file: nginx-src/build.yaml
  - put: nginx-docker
    params:
      build: nginx-build

- name: java
  plan:
  - aggregate:
      - get: common
      - get: java-src
        trigger: true
  - task: build-glibc
    file: common/glibc/build.yaml
  - task: build-java
    file: java-src/build.yaml
  - put: java-docker
    params:
      build: java-build

- name: kibana
  plan:
  - get: kibana-src
    trigger: true
  - task: build-kibana
    file: kibana-src/build.yaml
  - put: kibana-docker
    params:
      build: kibana-build

- name: alpine-build
  serial: true
  plan:
  - get: common
  - put: quay-io-desource-alpine-build
    params:
      build: common/build/alpine-build

- name: fedora-build
  serial: true
  plan:
  - get: common
  - put: quay-io-desource-fedora-build
    params:
      build: common/build/fedora-build
