groups:
- name: common
  jobs:
  - haproxy
  - nginx
  - skydns
- name: elk
  jobs:
  - java
  - elasticsearch
  - nodejs
  - kibana
- name: heka
  jobs:
  - heka

jobs:
- name: haproxy
  plan:
  - do:
    - aggregate:
      - get: container
        resource: haproxy-container
        trigger: true
      - get: libressl-ci
        trigger: true
      - get: libslz-ci
        trigger: true
      - get: liblua-ci
        trigger: true
    - aggregate:
      - task: libressl
        file: libressl-ci/build.yaml
      - task: libslz
        file: libslz-ci/build.yaml
      - task: liblua
        file: liblua-ci/build.yaml
    - task: haproxy
      file: container/build.yaml
    - put: haproxy-docker
      params:
        build: out
        tag: out/version

- name: nginx
  plan:
  - do:
    - aggregate:
      - get: container
        resource: nginx-container
        trigger: true
      - get: libressl-ci
        trigger: true
    - aggregate:
        - task: libressl
          file: libressl-ci/build.yaml
    - task: nginx
      file: container/build.yaml
    - put: nginx-docker
      params:
        build: out
        tag: out/version

- name: skydns
  plan:
  - do:
    - aggregate:
      - get: src
        resource: skydns-git
        trigger: true
      - get: container
        resource: skydns-container
        trigger: true
    - task: skydns
      file: container/build.yaml
    - put: skydns-docker
      params:
        build: out
        tag: out/version

- name: java
  plan:
  - do:
    - aggregate:
      - get: glibc-ci
        trigger: true
      - get: container
        resource: java-container
        trigger: true
    - task: glibc
      file: glibc-ci/build.yaml
    - task: java
      file: container/build.yaml
    - put: java-docker
      params:
        build: out
        tag: out/version

- name: elasticsearch
  plan:
  - do:
    - aggregate:
        - get: java-docker
          passed: [java]
          trigger: true
        - get: container
          resource: elasticsearch-container
          trigger: true
    - task: elasticsearch
      file: container/build.yaml
    - put: elasticsearch-docker
      params:
        build: out
        tag: out/version

- name: nodejs
  plan:
  - do:
    - get: container
      resource: nodejs-container
      trigger: true
    - task: nodejs
      file: container/build.yaml
    - put: nodejs-docker
      params:
        build: out
        tag: out/version

- name: kibana
  plan:
  - do:
    - aggregate:
      - get: nodejs-docker
        passed: [nodejs]
        trigger: true
      - get: container
        resource: kibana-container
        trigger: true
    - task: kibana
      file: container/build.yaml
    - put: kibana-docker
      params:
        build: out
        tag: out/version

- name: heka
  plan:
  - do:
    - aggregate:
      - get: src
        resource: heka-git
        trigger: true
      - get: heka-container-src
        trigger: true
    - task: heka
      file: heka-container-src/build.yaml
    - put: docker-heka
      params:
        build: out

resources:
- name: pipeline
  type: git
  source:
    uri: https://github.com/desource/pipeline.git

- name: slack
  type: slack-notification
  source:
    url: {{slack-notifications-url}}

- name: libressl-ci
  type: git
  source:
    uri: https://github.com/desource/libressl.git

- name: libslz-ci
  type: git
  source:
    uri: https://github.com/desource/libslz.git

- name: liblua-ci
  type: git
  source:
    uri: https://github.com/desource/liblua.git

- name: glibc-ci
  type: git
  source:
    uri: https://github.com/desource/glibc.git

- name: haproxy-container
  type: git
  source:
    uri: https://github.com/desource/haproxy-container.git

- name: haproxy-docker
  type: docker-image
  source:
    repository: quay.io/desource/haproxy
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: nginx-container
  type: git
  source:
    uri: https://github.com/desource/nginx-container.git

- name: nginx-docker
  type: docker-image
  source:
    repository: quay.io/desource/nginx
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: skydns-git
  type: git
  source:
    uri: https://github.com/skynetservices/skydns.git
    branch: 2.5.3a

- name: skydns-container
  type: git
  source:
    uri: https://github.com/desource/skydns-container.git

- name: java-container
  type: git
  source:
    uri: https://github.com/desource/java-container.git

- name: java-docker
  type: docker-image
  source:
    repository: quay.io/desource/java
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: elasticsearch-container
  type: git
  source:
    uri: https://github.com/desource/elasticsearch-container.git

- name: nodejs-container
  type: git
  source:
    uri: https://github.com/desource/nodejs-container.git

- name: kibana-container
  type: git
  source:
    uri: https://github.com/desource/kibana-container.git

- name: heka-git
  type: git
  source:
    uri: git@github.com:markuskobler/heka.git
    private_key: {{github-private-key}}
    branch: dev

- name: heka-container-src
  type: git
  source:
    uri: https://github.com/desource/container-heka.git

- name: elasticsearch-docker
  type: docker-image
  source:
    repository: quay.io/desource/elasticsearch
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: nodejs-docker
  type: docker-image
  source:
    repository: quay.io/desource/nodejs
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: kibana-docker
  type: docker-image
  source:
    repository: quay.io/desource/kibana
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: skydns-docker
  type: docker-image
  source:
    repository: quay.io/desource/skydns
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: docker-heka
  type: docker-image
  source:
    repository: quay.io/desource/heka
    username: {{quay-io-username}}
    password: {{quay-io-password}}

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
