groups:
- name: containers
  jobs:
    - haproxy
    - nginx
    - java
    - elasticsearch
    - kibana
    - heka
    - skydns
- name: base
  jobs:    
    - centos-7
    - ubuntu-trusty
    - ubuntu-xenial
- name: build
  jobs:
    - alpine-build
    - fedora-build

resources:
- name: pipeline
  type: git
  source:
    uri: git@github.com:desource/pipeline.git
    private_key: {{github-private-key}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-notifications-url}}

- name: haproxy-src
  type: git
  source:
    uri: https://github.com/desource/container-haproxy.git
    branch: concourse

- name: nginx-src
  type: git
  source:
    uri: https://github.com/desource/container-nginx.git
    branch: concourse

- name: java-src
  type: git
  source:
    uri: https://github.com/desource/container-java.git
    branch: concourse

- name: kibana-src
  type: git
  source:
    uri: https://github.com/desource/container-kibana.git
    branch: concourse

- name: elasticsearch-src
  type: git
  source:
    uri: https://github.com/desource/container-elasticsearch.git
    branch: concourse

- name: heka-container-src
  type: git
  source:
    uri: https://github.com/desource/container-heka.git
    branch: concourse

- name: skydns-container-src
  type: git
  source:
    uri: https://github.com/desource/container-skydns.git

- name: skydns-git
  type: git
  source:
    uri: https://github.com/skynetservices/skydns.git
    branch: 2.5.3a

- name: heka-git
  type: git
  source:
    uri: https://github.com/mozilla-services/heka.git

- name: heka-s3
  type: s3
  source:
    bucket: desource.net
    regexp: builds/heka/hekad-(.*)
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret-key}}

- name: alpine-build-image
  type: docker-image
  source:
    repository: quay.io/desource/alpine-build
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: fedora-build-image
  type: docker-image
  source:
    repository: quay.io/desource/fedora-build
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: centos-7-image
  type: docker-image
  source:
    repository: quay.io/desource/centos-7
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: ubuntu-trusty-image
  type: docker-image
  source:
    repository: quay.io/desource/ubuntu-trusty
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: ubuntu-xenial-image
  type: docker-image
  source:
    repository: quay.io/desource/ubuntu-xenial
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: haproxy-docker
  type: docker-image
  source:
    repository: quay.io/desource/haproxy
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: nginx-docker
  type: docker-image
  source:
    repository: quay.io/desource/nginx
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: java-docker
  type: docker-image
  source:
    repository: quay.io/desource/java
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: elasticsearch-docker
  type: docker-image
  source:
    repository: quay.io/desource/elasticsearch
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: kibana-docker
  type: docker-image
  source:
    repository: quay.io/desource/kibana
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: skydns-docker
  type: docker-image
  source:
    repository: quay.io/desource/skydns
    username: {{quay-io-username}}
    password: {{quay-io-password}}

- name: heka-docker
  type: docker-image
  source:
    repository: quay.io/desource/heka
    username: {{quay-io-username}}
    password: {{quay-io-password}}

jobs:
- name: haproxy
  plan:
  - aggregate:
      - get: pipeline
      - get: haproxy-src
        trigger: true
  - aggregate:
      - task: build-libressl
        file: pipeline/libressl/build.yaml
      - task: build-lua
        file: pipeline/lua/build.yaml
      - task: build-libslz
        file: pipeline/libslz/build.yaml
  - task: build-haproxy
    file: haproxy-src/build.yaml
  - put: haproxy-docker
    params:
      build: haproxy-build

- name: nginx
  plan:
  - aggregate:
      - get: pipeline
      - get: nginx-src
        trigger: true
  - aggregate:
      - task: build-libressl
        file: pipeline/libressl/build.yaml
  - task: build-nginx
    file: nginx-src/build.yaml
  - put: nginx-docker
    params:
      build: nginx-build
  - put: slack-alert
    params:
      channel: '#general'
      username: concourse
      icon_emoji: concourse
      text: build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: java
  plan:
  - aggregate:
      - get: pipeline
      - get: java-src
        trigger: true
  - task: build-glibc
    file: pipeline/glibc/build.yaml
  - task: build-java
    file: java-src/build.yaml
  - put: java-docker
    params:
      build: java-build
  - put: slack-alert
    params:
      channel: '#general'
      username: concourse
      icon_emoji: concourse
      text: build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: elasticsearch
  plan:
  - aggregate:
      - get: java-docker
        passed: [java]
      - get: elasticsearch-src
        trigger: true
  - task: build-elasticsearch
    file: elasticsearch-src/build.yaml
  - put: elasticsearch-docker
    params:
      build: elasticsearch-build
  - put: slack-alert
    params:
      channel: '#general'
      username: concourse
      icon_emoji: concourse
      text: build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: kibana
  plan:
  - get: kibana-src
    trigger: true
  - task: build-kibana
    file: kibana-src/build.yaml
  - put: kibana-docker
    params:
      build: kibana-build
  - put: slack-alert
    params:
      channel: '#general'
      username: concourse
      icon_emoji: concourse
      text: build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: heka
  plan:
  - aggregate:
      - get: heka-git
      - get: heka-container-src
        trigger: true
  - task: build-heka
    file: heka-container-src/build.yaml
  - put: heka-s3
    params:
      file: heka-build/builds/heka/**
  - put: slack-alert
    params:
      channel: '#general'
      username: concourse
      icon_emoji: concourse
      text: build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: skydns
  plan:
  - aggregate:
      - get: skydns-git
      - get: skydns-container-src
        trigger: true
  - task: build-skydns
    file: skydns-container-src/build.yaml
  - put: skydns-docker
    params:
      build: skydns-build
  - put: slack-alert
    params:
      channel: '#general'
      username: concourse
      icon_emoji: concourse
      text: build https://ci.desource.net/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME


- name: alpine-build
  serial: true
  plan:
  - get: pipeline
  - put: alpine-build-image
    params:
      build: pipeline/build/alpine-build

- name: fedora-build
  serial: true
  plan:
  - get: pipeline
  - put: fedora-build-image
    params:
      build: pipeline/build/fedora-build
      
- name: centos-7
  serial: true
  plan:
  - get: pipeline
  - put: centos-7-image
    params:
      build: pipeline/base/centos-7
      
- name: ubuntu-trusty
  serial: true
  plan:
  - get: pipeline
  - put: ubuntu-trusty-image
    params:
      build: pipeline/base/ubuntu-trusty
      
- name: ubuntu-xenial
  serial: true
  plan:
  - get: pipeline
  - put: ubuntu-xenial-image
    params:
      build: pipeline/base/ubuntu-xenial

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
