jobs:
- name: terraform
  serial: true
  plan:
  - aggregate:
    - get: pipeline
    - get: terraform-src
      trigger: true
  - task: terraform
    file: pipeline/terraform/build.yaml
  - put: docker-terraform
    params:
      build: out

resources:
- name: pipeline
  type: git
  source:
    uri: https://github.com/desource/pipeline.git

- name: terraform-src
  type: git
  source:
    uri: https://github.com/hmrc/terraform.git
    branch: hmrc-release

- name: docker-terraform
  type: docker-image
  source:
    repository: quay.io/desource/terraform
    username: {{quay-io-username}}
    password: {{quay-io-password}}
