---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/desource/alpine-build

inputs:
  - name: common
    path: src

outputs:
  - name: lua-build
  
run:
  path: ./src/lua/build.sh
