---
platform: linux
image_resource:
  type: docker-image
  source: {repository: golang, tag: 1.7-onbuild}

run:
  path: pipeline/terraform/build.sh
  
inputs:
- name: pipeline
- name: terraform-src
  path: go/src/github.com/hashicorp/terraform

outputs:
- name: out
