---
platform: linux
image_resource:
  type: docker-image
  source: {repository: quay.io/desource/alpine, tag: build}

inputs:
  - name: pipeline
    path: src

outputs:
  - name: libslz-build
  
run:
  path: ./src/libslz/build.sh

