---
platform: linux

image_resource:
  type: docker-image
  source: {repository: quay.io/desource/alpine, tag: build}

inputs:
  - name: pipeline
    path: src

outputs:
  - name: pcre-build
  
run:
  path: ./src/pcre/build.sh

