---
platform: linux
image_resource:
  type: docker-image
  source: {repository: quay.io/desource/fedora, tag: build}

run:
  path: src/concourse/build.sh
  
inputs:
  - name: pipeline
    path: src

outputs:
  - name: out
